# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2022-09-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.fetch_settlements_request_filters import FetchSettlementsRequestFilters  # noqa: E501
from cashfree_pg.rest import ApiException

class TestFetchSettlementsRequestFilters(unittest.TestCase):
    """FetchSettlementsRequestFilters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FetchSettlementsRequestFilters
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchSettlementsRequestFilters`
        """
        model = cashfree_pg.models.fetch_settlements_request_filters.FetchSettlementsRequestFilters()  # noqa: E501
        if include_optional :
            return FetchSettlementsRequestFilters(
                cf_settlement_ids = [
                    56
                    ], 
                settlement_utrs = [
                    ''
                    ], 
                start_date = '', 
                end_date = ''
            )
        else :
            return FetchSettlementsRequestFilters(
        )
        """

    def testFetchSettlementsRequestFilters(self):
        """Test FetchSettlementsRequestFilters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
