# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2023-08-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashfree_pg.models.subscription_customer_details import SubscriptionCustomerDetails

class TestSubscriptionCustomerDetails(unittest.TestCase):
    """SubscriptionCustomerDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionCustomerDetails:
        """Test SubscriptionCustomerDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionCustomerDetails`
        """
        model = SubscriptionCustomerDetails()
        if include_optional:
            return SubscriptionCustomerDetails(
                customer_name = '',
                customer_email = '',
                customer_phone = '',
                customer_bank_account_holder_name = '',
                customer_bank_account_number = '',
                customer_bank_ifsc = '',
                customer_bank_code = '',
                customer_bank_account_type = ''
            )
        else:
            return SubscriptionCustomerDetails(
                customer_email = '',
                customer_phone = '',
        )
        """

    def testSubscriptionCustomerDetails(self):
        """Test SubscriptionCustomerDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
