# coding: utf-8

"""
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

The version of the OpenAPI document: 2026-01-01
Contact: developers@cashfree.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.vendor_recon200_response import VendorRecon200Response  # noqa: E501
from cashfree_pg.rest import ApiException

class TestVendorRecon200Response(unittest.TestCase):
    """VendorRecon200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VendorRecon200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VendorRecon200Response`
        """
        model = cashfree_pg.models.vendor_recon200_response.VendorRecon200Response()  # noqa: E501
        if include_optional :
            return VendorRecon200Response(
                cursor = '', 
                data = [
                    cashfree_pg.models.vendor_recon200_response_data_inner.VendorRecon200Response_data_inner(
                        amount = 1.337, 
                        settlement_eligibility_time = '', 
                        merchant_order_id = '', 
                        tx_time = '', 
                        settlement_id = 56, 
                        settled = True, 
                        fee = '', 
                        tax = '', 
                        entity_id = '', 
                        type = '', 
                        merchant_vendor_id = '', 
                        added_on_time = '', 
                        settlement_time = '', 
                        settlement_utr = '', 
                        currency = '', 
                        debit = '', 
                        credit = '', 
                        refund_arn = '', )
                    ], 
                limit = 56
            )
        else :
            return VendorRecon200Response(
        )
        """

    def testVendorRecon200Response(self):
        """Test VendorRecon200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
