# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2023-08-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashfree_pg.models.terminal_transaction_entity import TerminalTransactionEntity

class TestTerminalTransactionEntity(unittest.TestCase):
    """TerminalTransactionEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TerminalTransactionEntity:
        """Test TerminalTransactionEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TerminalTransactionEntity`
        """
        model = TerminalTransactionEntity()
        if include_optional:
            return TerminalTransactionEntity(
                cf_payment_id = '',
                payment_amount = 56,
                payment_method = '',
                payment_url = '',
                qrcode = '',
                timeout = ''
            )
        else:
            return TerminalTransactionEntity(
        )
        """

    def testTerminalTransactionEntity(self):
        """Test TerminalTransactionEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
