# coding: utf-8

"""
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

The version of the OpenAPI document: 2026-01-01
Contact: developers@cashfree.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.instrument_entity_for_all_saved_card import InstrumentEntityForAllSavedCard  # noqa: E501
from cashfree_pg.rest import ApiException

class TestInstrumentEntityForAllSavedCard(unittest.TestCase):
    """InstrumentEntityForAllSavedCard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InstrumentEntityForAllSavedCard
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstrumentEntityForAllSavedCard`
        """
        model = cashfree_pg.models.instrument_entity_for_all_saved_card.InstrumentEntityForAllSavedCard()  # noqa: E501
        if include_optional :
            return InstrumentEntityForAllSavedCard(
                customer_id = '', 
                afa_reference = '', 
                instrument_id = '', 
                instrument_type = '', 
                instrument_uid = '', 
                instrument_display = '', 
                instrument_status = '', 
                created_at = '', 
                instrument_meta = cashfree_pg.models.instrument_meta.InstrumentMeta(
                    card_network = '', 
                    card_bank_name = '', 
                    card_country = '', 
                    card_type = '', 
                    card_sub_type = '', 
                    card_token_details = cashfree_pg.models.saved_instrument_meta_card_token_details.SavedInstrumentMeta_card_token_details(
                        par = '', 
                        expiry_month = '', 
                        expiry_year = '', ), )
            )
        else :
            return InstrumentEntityForAllSavedCard(
        )
        """

    def testInstrumentEntityForAllSavedCard(self):
        """Test InstrumentEntityForAllSavedCard"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
