# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2023-08-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashfree_pg.api.soft_pos_api import SoftPOSApi


class TestSoftPOSApi(unittest.TestCase):
    """SoftPOSApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SoftPOSApi()

    def tearDown(self) -> None:
        pass

    def test_spos_create_terminal(self) -> None:
        """Test case for spos_create_terminal

        Create Terminal
        """
        pass

    def test_spos_create_terminal_transaction(self) -> None:
        """Test case for spos_create_terminal_transaction

        Create Terminal Transaction
        """
        pass

    def test_spos_demap_soundbox_vpa(self) -> None:
        """Test case for spos_demap_soundbox_vpa

        Demap Soundbox Vpa
        """
        pass

    def test_spos_fetch_terminal(self) -> None:
        """Test case for spos_fetch_terminal

        Get Terminal Status using Phone Number
        """
        pass

    def test_spos_fetch_terminal_qr_codes(self) -> None:
        """Test case for spos_fetch_terminal_qr_codes

        Fetch Terminal QR Codes
        """
        pass

    def test_spos_fetch_terminal_soundbox_vpa(self) -> None:
        """Test case for spos_fetch_terminal_soundbox_vpa

        Fetch Terminal Soundbox vpa
        """
        pass

    def test_spos_fetch_terminal_transaction(self) -> None:
        """Test case for spos_fetch_terminal_transaction

        Get Terminal Transaction
        """
        pass

    def test_spos_onboard_soundbox_vpa(self) -> None:
        """Test case for spos_onboard_soundbox_vpa

        Onboard Soundbox Vpa
        """
        pass

    def test_spos_update_soundbox_vpa(self) -> None:
        """Test case for spos_update_soundbox_vpa

        Update Soundbox Vpa
        """
        pass

    def test_spos_update_terminal(self) -> None:
        """Test case for spos_update_terminal

        Update Terminal
        """
        pass

    def test_spos_update_terminal_status(self) -> None:
        """Test case for spos_update_terminal_status

        Update Terminal Status
        """
        pass

    def test_spos_upload_terminal_docs(self) -> None:
        """Test case for spos_upload_terminal_docs

        Upload Terminal Docs
        """
        pass


if __name__ == '__main__':
    unittest.main()
