# coding: utf-8

"""
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

The version of the OpenAPI document: 2026-01-01
Contact: developers@cashfree.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.auth_response_enach import AuthResponseEnach  # noqa: E501
from cashfree_pg.rest import ApiException

class TestAuthResponseEnach(unittest.TestCase):
    """AuthResponseEnach unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AuthResponseEnach
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthResponseEnach`
        """
        model = cashfree_pg.models.auth_response_enach.AuthResponseEnach()  # noqa: E501
        if include_optional :
            return AuthResponseEnach(
                channel = '', 
                auth_mode = '', 
                account_type = '', 
                account_number = '', 
                account_ifsc = '', 
                account_holder_name = '', 
                account_bank_code = ''
            )
        else :
            return AuthResponseEnach(
        )
        """

    def testAuthResponseEnach(self):
        """Test AuthResponseEnach"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
