# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2022-09-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.link_entity import LinkEntity  # noqa: E501
from cashfree_pg.rest import ApiException

class TestLinkEntity(unittest.TestCase):
    """LinkEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LinkEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkEntity`
        """
        model = cashfree_pg.models.link_entity.LinkEntity()  # noqa: E501
        if include_optional :
            return LinkEntity(
                cf_link_id = 56, 
                link_id = '', 
                link_status = '', 
                link_currency = '', 
                link_amount = 1.337, 
                link_amount_paid = 1.337, 
                link_partial_payments = True, 
                link_minimum_partial_amount = 1.337, 
                link_purpose = '', 
                link_created_at = '', 
                customer_details = {"customer_name":"John Doe","customer_phone":"9999999999","customer_email":"john@cashfree.com"}, 
                link_meta = {"key_1":"value_1","key_2":"value_2"}, 
                link_url = '', 
                link_expiry_time = '', 
                link_notes = {"key_1":"value_1","key_2":"value_2"}, 
                link_auto_reminders = True, 
                link_notify = {"send_sms":false,"send_email":true}
            )
        else :
            return LinkEntity(
        )
        """

    def testLinkEntity(self):
        """Test LinkEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
