# coding: utf-8

"""
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

The version of the OpenAPI document: 2026-01-01
Contact: developers@cashfree.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.get_all_terminal_transaction_request import GetAllTerminalTransactionRequest  # noqa: E501
from cashfree_pg.rest import ApiException

class TestGetAllTerminalTransactionRequest(unittest.TestCase):
    """GetAllTerminalTransactionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetAllTerminalTransactionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAllTerminalTransactionRequest`
        """
        model = cashfree_pg.models.get_all_terminal_transaction_request.GetAllTerminalTransactionRequest()  # noqa: E501
        if include_optional :
            return GetAllTerminalTransactionRequest(
                filter = {"start_date":"2023-08-04T13:12:58+05:30","end_date":"2023-08-04T13:12:58+05:30","cf_terminal_id":1234,"terminal_vpa":"cf.epos@cash","terminal_phone_no":"9696969696","payment_status":"SUCCESS","payment_group":"UPI","sort_by":"start_date","sort_order":"ASC"}, 
                pagination = {"page_number":1,"page_size":50}
            )
        else :
            return GetAllTerminalTransactionRequest(
        )
        """

    def testGetAllTerminalTransactionRequest(self):
        """Test GetAllTerminalTransactionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
