# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2025-01-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.payment_entity import PaymentEntity  # noqa: E501
from cashfree_pg.rest import ApiException

class TestPaymentEntity(unittest.TestCase):
    """PaymentEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PaymentEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentEntity`
        """
        model = cashfree_pg.models.payment_entity.PaymentEntity()  # noqa: E501
        if include_optional :
            return PaymentEntity(
                cf_payment_id = '', 
                order_id = '', 
                entity = '', 
                error_details = {"error_code":"TRANSACTION_DECLINED","error_description":"issuer bank or payment service provider declined the transaction","error_reason":"auth_declined","error_source":"customer","error_code_raw":"ZM","error_description_raw":"INVALID / INCORRECT MPIN","error_subcode_raw":""}, 
                is_captured = True, 
                order_amount = 1.337, 
                payment_group = '', 
                payment_currency = '', 
                payment_amount = 1.337, 
                payment_time = '', 
                payment_completion_time = '', 
                payment_status = 'SUCCESS', 
                payment_message = '', 
                bank_reference = '', 
                auth_id = '', 
                order_currency = '', 
                authorization = {"action":"CAPTURE","status":"PENDING","captured_amount":100,"start_time":"2022-02-09T18:04:34+05:30","end_time":"2022-02-19T18:04:34+05:30","approve_by":"2022-02-09T18:04:34+05:30","action_reference":"6595231908096894505959","action_time":"2022-08-03T16:09:51"}, 
                payment_method = None, 
                international_payment = cashfree_pg.models.international_payment.InternationalPayment(
                    international = True, ), 
                payment_gateway_details = cashfree_pg.models.payment_gateway_details.PaymentGatewayDetails(
                    gateway_name = '', 
                    gateway_order_id = '', 
                    gateway_payment_id = '', 
                    gateway_order_reference_id = '', 
                    gateway_status_code = '', 
                    gateway_settlement = '', 
                    gateway_reference_name = '', ), 
                payment_surcharge = cashfree_pg.models.payment_entity_payment_surcharge.PaymentEntity_payment_surcharge(
                    payment_surcharge_service_charge = 1.337, 
                    payment_surcharge_service_tax = 1.337, )
            )
        else :
            return PaymentEntity(
        )
        """

    def testPaymentEntity(self):
        """Test PaymentEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
