# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2023-08-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashfree_pg.api.settlements_api import SettlementsApi


class TestSettlementsApi(unittest.TestCase):
    """SettlementsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettlementsApi()

    def tearDown(self) -> None:
        pass

    def test_mark_for_settlement(self) -> None:
        """Test case for mark_for_settlement

        Mark Order For Settlement
        """
        pass

    def test_p_g_order_fetch_settlement(self) -> None:
        """Test case for p_g_order_fetch_settlement

        Get Settlements by Order ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
