# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2022-09-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.offer_queries import OfferQueries  # noqa: E501
from cashfree_pg.rest import ApiException

class TestOfferQueries(unittest.TestCase):
    """OfferQueries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OfferQueries
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OfferQueries`
        """
        model = cashfree_pg.models.offer_queries.OfferQueries()  # noqa: E501
        if include_optional :
            return OfferQueries(
                order_id = 'order_413462PK1RI1IwYB1X69LgzUQWiSxYDF', 
                amount = 100
            )
        else :
            return OfferQueries(
        )
        """

    def testOfferQueries(self):
        """Test OfferQueries"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
