# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2022-09-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import cashfree_pg
from cashfree_pg.api.payment_links_api import PaymentLinksApi  # noqa: E501
from cashfree_pg.rest import ApiException


class TestPaymentLinksApi(unittest.TestCase):
    """PaymentLinksApi unit test stubs"""

    def setUp(self):
        self.api = cashfree_pg.api.payment_links_api.PaymentLinksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_p_g_cancel_link(self):
        """Test case for p_g_cancel_link

        Cancel Payment Link  # noqa: E501
        """
        pass

    def test_p_g_create_link(self):
        """Test case for p_g_create_link

        Create Payment Link  # noqa: E501
        """
        pass

    def test_p_g_fetch_link(self):
        """Test case for p_g_fetch_link

        Fetch Payment Link Details  # noqa: E501
        """
        pass

    def test_p_g_link_fetch_orders(self):
        """Test case for p_g_link_fetch_orders

        Get Orders for a Payment Link  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
