# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2025-01-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.settlement_recon_entity_data_inner_settlement_details import SettlementReconEntityDataInnerSettlementDetails  # noqa: E501
from cashfree_pg.rest import ApiException

class TestSettlementReconEntityDataInnerSettlementDetails(unittest.TestCase):
    """SettlementReconEntityDataInnerSettlementDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SettlementReconEntityDataInnerSettlementDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettlementReconEntityDataInnerSettlementDetails`
        """
        model = cashfree_pg.models.settlement_recon_entity_data_inner_settlement_details.SettlementReconEntityDataInnerSettlementDetails()  # noqa: E501
        if include_optional :
            return SettlementReconEntityDataInnerSettlementDetails(
                cf_settlement_id = '', 
                settlement_date = '', 
                utr = '', 
                split_service_charge = 1.337, 
                split_service_tax = 1.337, 
                vendor_commission = 1.337, 
                payment_from = '', 
                payment_till = '', 
                reason = '', 
                remarks = '', 
                service_charge = 1.337, 
                service_tax = 1.337, 
                settlement_charge = 1.337, 
                settlement_initiated_on = '', 
                settlement_tax = 1.337, 
                settlement_type = ''
            )
        else :
            return SettlementReconEntityDataInnerSettlementDetails(
        )
        """

    def testSettlementReconEntityDataInnerSettlementDetails(self):
        """Test SettlementReconEntityDataInnerSettlementDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
