# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2023-08-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.static_split_response import StaticSplitResponse  # noqa: E501
from cashfree_pg.rest import ApiException

class TestStaticSplitResponse(unittest.TestCase):
    """StaticSplitResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test StaticSplitResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StaticSplitResponse`
        """
        model = cashfree_pg.models.static_split_response.StaticSplitResponse()  # noqa: E501
        if include_optional :
            return StaticSplitResponse(
                active = True, 
                terminal_id = '', 
                terminal_reference_id = 1.337, 
                product_type = '', 
                scheme = [
                    cashfree_pg.models.static_split_response_scheme_inner.StaticSplitResponse_scheme_inner(
                        merchant_vendor_id = '', 
                        percentage = '', )
                    ], 
                added_on = ''
            )
        else :
            return StaticSplitResponse(
        )
        """

    def testStaticSplitResponse(self):
        """Test StaticSplitResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
