# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2023-08-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashfree_pg.models.banktransfer_payment_method import BanktransferPaymentMethod

class TestBanktransferPaymentMethod(unittest.TestCase):
    """BanktransferPaymentMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BanktransferPaymentMethod:
        """Test BanktransferPaymentMethod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BanktransferPaymentMethod`
        """
        model = BanktransferPaymentMethod()
        if include_optional:
            return BanktransferPaymentMethod(
                banktransfer = {"channel":"link"}
            )
        else:
            return BanktransferPaymentMethod(
                banktransfer = {"channel":"link"},
        )
        """

    def testBanktransferPaymentMethod(self):
        """Test BanktransferPaymentMethod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
