# coding: utf-8

"""
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

The version of the OpenAPI document: 2026-01-01
Contact: developers@cashfree.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.authorization_details import AuthorizationDetails  # noqa: E501
from cashfree_pg.rest import ApiException

class TestAuthorizationDetails(unittest.TestCase):
    """AuthorizationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AuthorizationDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthorizationDetails`
        """
        model = cashfree_pg.models.authorization_details.AuthorizationDetails()  # noqa: E501
        if include_optional :
            return AuthorizationDetails(
                authorization_amount = 1.337, 
                authorization_amount_refund = True, 
                authorization_reference = '', 
                authorization_time = '2025-06-01T10:20:12+05:30', 
                authorization_status = '', 
                payment_id = '', 
                payment_group = '', 
                payment_method = cashfree_pg.models.authorization_details_payment_method.AuthorizationDetails_payment_method(
                    upi = cashfree_pg.models.upi_auth_response.Upi Auth Response(
                        channel = '', 
                        upi_id = '', 
                        upi_instrument = '', 
                        upi_instrument_number = '', 
                        upi_payer_account_number = '', 
                        upi_payer_ifsc = '', ), 
                    enach = cashfree_pg.models.enach_auth_response.Enach Auth Response(
                        channel = '', 
                        auth_mode = '', 
                        account_type = '', 
                        account_number = '', 
                        account_ifsc = '', 
                        account_holder_name = '', 
                        account_bank_code = '', ), 
                    pnach = cashfree_pg.models.pnach_auth_response.Pnach Auth Response(
                        channel = '', 
                        mandate_creation_date = '2025-06-01T10:20:12+05:30', 
                        mandate_start_date = '2025-06-01T10:20:12+05:30', 
                        account_type = '', 
                        account_number = '', 
                        account_ifsc = '', 
                        account_holder_name = '', 
                        account_bank_code = '', ), 
                    card = cashfree_pg.models.card_auth_response.Card Auth Response(
                        channel = '', 
                        card_number = '', 
                        card_network = '', 
                        card_type = '', 
                        card_sub_type = '', 
                        card_country = '', 
                        card_bank_name = '', 
                        card_network_reference_id = '', 
                        instrument_id = '', ), )
            )
        else :
            return AuthorizationDetails(
        )
        """

    def testAuthorizationDetails(self):
        """Test AuthorizationDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
