# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2023-08-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.eligibility_method_item import EligibilityMethodItem  # noqa: E501
from cashfree_pg.rest import ApiException

class TestEligibilityMethodItem(unittest.TestCase):
    """EligibilityMethodItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EligibilityMethodItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EligibilityMethodItem`
        """
        model = cashfree_pg.models.eligibility_method_item.EligibilityMethodItem()  # noqa: E501
        if include_optional :
            return EligibilityMethodItem(
                eligibility = True, 
                entity_type = '', 
                entity_value = '', 
                entity_details = cashfree_pg.models.eligibility_method_item_entity_details.EligibilityMethodItem_entity_details(
                    account_types = [
                        ''
                        ], 
                    frequent_bank_details = [
                        cashfree_pg.models.subscription_bank_details.SubscriptionBankDetails(
                            bank_id = '', 
                            bank_name = '', 
                            account_auth_modes = [
                                ''
                                ], )
                        ], 
                    all_bank_details = [
                        cashfree_pg.models.subscription_bank_details.SubscriptionBankDetails(
                            bank_id = '', 
                            bank_name = '', )
                        ], 
                    available_handles = [
                        cashfree_pg.models.eligibility_method_item_entity_details_available_handles_inner.EligibilityMethodItem_entity_details_available_handles_inner(
                            handle = '', 
                            application = '', )
                        ], 
                    allowed_card_types = [
                        ''
                        ], )
            )
        else :
            return EligibilityMethodItem(
        )
        """

    def testEligibilityMethodItem(self):
        """Test EligibilityMethodItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
