/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Adjust Vendor Balance Request
 * @export
 * @interface AdjustVendorBalanceRequest
 */
export interface AdjustVendorBalanceRequest {
    /**
     * Mention to whom you want to transfer the on demand balance. Possible values - MERCHANT, VENDOR.
     * @type {str}
     * @memberof AdjustVendorBalanceRequest
     */
    'transfer_from': str;
    /**
     * Mention the type of transfer. Possible values: ON_DEMAND.
     * @type {str}
     * @memberof AdjustVendorBalanceRequest
     */
    'transfer_type': str;
    /**
     * Mention the on demand transfer amount.
     * @type {float}
     * @memberof AdjustVendorBalanceRequest
     */
    'transfer_amount': float;
    /**
     * Mention remarks if any for the on demand transfer.
     * @type {str}
     * @memberof AdjustVendorBalanceRequest
     */
    'remark'?: str;
    /**
     * Provide additional data fields using tags.
     * @type {object}
     * @memberof AdjustVendorBalanceRequest
     */
    'tags'?: object;
}
