/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request body for cardless emi payment method
 * @export
 * @interface CardlessEMI
 */
export interface CardlessEMI {
    /**
     * The channel for cardless EMI is always `link`
     * @type {str}
     * @memberof CardlessEMI
     */
    'channel'?: str;
    /**
     * One of [`flexmoney`, `zestmoney`, `hdfc`, `icici`, `cashe`, `idfc`, `kotak`, `snapmint`, `bharatx`]
     * @type {str}
     * @memberof CardlessEMI
     */
    'provider'?: ProviderEnum;
    /**
     * Customers phone number for this payment instrument. If the customer is not eligible you will receive a 400 error with type as 'invalid_request_error' and code as 'invalid_request_error'
     * @type {str}
     * @memberof CardlessEMI
     */
    'phone'?: str;
    /**
     * EMI tenure for the selected provider. This is mandatory when provider is one of [`hdfc`, `icici`, `cashe`, `idfc`, `kotak`]
     * @type {int}
     * @memberof CardlessEMI
     */
    'emi_tenure'?: int;
}

export const ProviderEnum = {
    'flexmoney': 'flexmoney',
    'zestmoney': 'zestmoney',
    'hdfc': 'hdfc',
    'icici': 'icici',
    'cashe': 'cashe',
    'idfc': 'idfc',
    'kotak': 'kotak',
    'snapmint': 'snapmint',
    'bharatx': 'bharatx',
    'unknown_default_open_api': 'unknown_default_open_api'
} as const;

export type ProviderEnum = typeof ProviderEnum[keyof typeof ProviderEnum];

