/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * payment method card.
 * @export
 * @interface CreateSubscriptionPaymentRequestCard
 */
export interface CreateSubscriptionPaymentRequestCard {
    /**
     * Card CVV
     * @type {str}
     * @memberof CreateSubscriptionPaymentRequestCard
     */
    'card_cvv'?: str;
    /**
     * Card expiry month
     * @type {str}
     * @memberof CreateSubscriptionPaymentRequestCard
     */
    'card_expiry_mm'?: str;
    /**
     * Card expiry year
     * @type {str}
     * @memberof CreateSubscriptionPaymentRequestCard
     */
    'card_expiry_yy'?: str;
    /**
     * Card holder name
     * @type {str}
     * @memberof CreateSubscriptionPaymentRequestCard
     */
    'card_holder_name'?: str;
    /**
     * Card network
     * @type {str}
     * @memberof CreateSubscriptionPaymentRequestCard
     */
    'card_network'?: str;
    /**
     * Card number
     * @type {str}
     * @memberof CreateSubscriptionPaymentRequestCard
     */
    'card_number'?: str;
    /**
     * Card type
     * @type {str}
     * @memberof CreateSubscriptionPaymentRequestCard
     */
    'card_type'?: str;
    /**
     * Channel. can be link
     * @type {str}
     * @memberof CreateSubscriptionPaymentRequestCard
     */
    'channel'?: str;
}
