# coding: utf-8

"""
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

The version of the OpenAPI document: 2026-01-01
Contact: developers@cashfree.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime


from pydantic import validate_arguments, ValidationError, Field, StrictStr, StrictBytes, StrictInt, StrictFloat, StrictBool, field_validator, BaseModel
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

class CreateSubscriptionPaymentRequestEnachEnach(BaseModel):
    """
    CreateSubscriptionPaymentRequestEnachEnach
    """
    account_bank_code: Optional[StrictStr] = Field(default=None, description="Account bank code (mandatory). Consists of the first four alphabetic characters of the IFSC.")
    account_holder_name: Optional[StrictStr] = Field(default=None, description="Account holder name.")
    account_ifsc: Optional[StrictStr] = Field(default=None, description="Account IFSC (optional). Complete 11-character alphanumeric code.")
    account_number: Optional[StrictStr] = Field(default=None, description="Account number.")
    account_type: Optional[StrictStr] = Field(default=None, description="Account type.")
    auth_mode: Optional[StrictStr] = Field(default=None, description="Authentication mode. can be `debit_card`, `aadhaar`, or `net_banking`.")
    channel: Optional[StrictStr] = Field(default=None, description="Channel. can be link.")
    __properties = ["account_bank_code", "account_holder_name", "account_ifsc", "account_number", "account_type", "auth_mode", "channel"]

    @field_validator('account_type')
    def account_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('SAVINGS', 'CURRENT'):
            raise ValueError("must be one of enum values ('SAVINGS', 'CURRENT')")
        return value

    # Updated to Pydantic v2
    """Pydantic configuration"""
    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateSubscriptionPaymentRequestEnachEnach:
        """Create an instance of CreateSubscriptionPaymentRequestEnachEnach from a JSON string"""
        return cls.from_dict(json.loads(json_str))
    
    @classmethod
    def from_json_for_one_of(cls, json_str: str) -> CreateSubscriptionPaymentRequestEnachEnach:
        """Create an instance of CreateSubscriptionPaymentRequestEnachEnach from a JSON string"""
        temp_dict = json.loads(json_str)
        if "account_bank_code, account_holder_name, account_ifsc, account_number, account_type, auth_mode, channel" in temp_dict.keys():
            return cls.from_dict(json.loads(json_str))
        return None

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateSubscriptionPaymentRequestEnachEnach:
        """Create an instance of CreateSubscriptionPaymentRequestEnachEnach from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateSubscriptionPaymentRequestEnachEnach.parse_obj(obj)

        _obj = CreateSubscriptionPaymentRequestEnachEnach.parse_obj({
            "account_bank_code": obj.get("account_bank_code"),
            "account_holder_name": obj.get("account_holder_name"),
            "account_ifsc": obj.get("account_ifsc"),
            "account_number": obj.get("account_number"),
            "account_type": obj.get("account_type"),
            "auth_mode": obj.get("auth_mode"),
            "channel": obj.get("channel")
        })
        return _obj


# Pydantic v2: resolve forward references & Annotated types
CreateSubscriptionPaymentRequestEnachEnach.model_rebuild()

