/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Crytogram Card object
 * @export
 * @interface CryptogramEntity
 */
export interface CryptogramEntity {
    /**
     * instrument_id of saved instrument
     * @type {str}
     * @memberof CryptogramEntity
     */
    'instrument_id'?: str;
    /**
     * TRID issued by card networks
     * @type {str}
     * @memberof CryptogramEntity
     */
    'token_requestor_id'?: str;
    /**
     * token pan number
     * @type {str}
     * @memberof CryptogramEntity
     */
    'card_number'?: str;
    /**
     * token pan expiry month
     * @type {str}
     * @memberof CryptogramEntity
     */
    'card_expiry_mm'?: str;
    /**
     * token pan expiry year
     * @type {str}
     * @memberof CryptogramEntity
     */
    'card_expiry_yy'?: str;
    /**
     * cryptogram
     * @type {str}
     * @memberof CryptogramEntity
     */
    'cryptogram'?: str;
    /**
     * last 4 digits of original card number
     * @type {str}
     * @memberof CryptogramEntity
     */
    'card_display'?: str;
}
