/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request body to demap soundbox vpa
 * @export
 * @interface DemapSoundboxVpaRequest
 */
export interface DemapSoundboxVpaRequest {
    /**
     * cashfree terminal id.
     * @type {str}
     * @memberof DemapSoundboxVpaRequest
     */
    'cf_terminal_id': str;
    /**
     * Device Serial No of soundbox that need to demap.
     * @type {str}
     * @memberof DemapSoundboxVpaRequest
     */
    'device_serial_no': str;
}
