/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Single EMI object
 * @export
 * @interface EMIPlansArray
 */
export interface EMIPlansArray {
    /**
     * 
     * @type {int}
     * @memberof EMIPlansArray
     */
    'tenure'?: int;
    /**
     * 
     * @type {float}
     * @memberof EMIPlansArray
     */
    'interest_rate'?: float;
    /**
     * 
     * @type {str}
     * @memberof EMIPlansArray
     */
    'currency'?: str;
    /**
     * 
     * @type {int}
     * @memberof EMIPlansArray
     */
    'emi'?: int;
    /**
     * 
     * @type {int}
     * @memberof EMIPlansArray
     */
    'total_interest'?: int;
    /**
     * 
     * @type {int}
     * @memberof EMIPlansArray
     */
    'total_amount'?: int;
}
