/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ESOrderReconResponseDataInner
 */
export interface ESOrderReconResponseDataInner {
    /**
     * 
     * @type {float}
     * @memberof ESOrderReconResponseDataInner
     */
    'amount'?: float;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'settlement_eligibility_time'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'status'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'merchant_order_id'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'tx_time'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'settled'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'entity_id'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'merchant_settlement_utr'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'currency'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'sale_type'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'customer_name'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'customer_email'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'customer_phone'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'merchant_vendor_commission'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'split_service_charge'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'split_service_tax'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'pg_service_tax'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'pg_service_charge'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'pg_charge_postpaid'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'merchant_settlement_id'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'added_on'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'tags'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'entity_type'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'settlement_initiated_on'?: str;
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'settlement_time'?: str;
    /**
     * 
     * @type {List[ESOrderReconResponseDataInnerOrderSplitsInner]}
     * @memberof ESOrderReconResponseDataInner
     */
    'order_splits'?: List[ESOrderReconResponseDataInnerOrderSplitsInner];
    /**
     * 
     * @type {str}
     * @memberof ESOrderReconResponseDataInner
     */
    'eligible_split_balance'?: str;
}
