/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specify either the Settlement ID, Settlement UTR, or start date and end date to fetch the settlement details.
 * @export
 * @interface FetchSettlementsRequestFilters
 */
export interface FetchSettlementsRequestFilters {
    /**
     * List of settlement IDs for which you want the settlement reconciliation details.
     * @type {List[str]}
     * @memberof FetchSettlementsRequestFilters
     */
    'cf_settlement_ids'?: List[str];
    /**
     * List of settlement UTRs for which you want the settlement reconciliation details.
     * @type {List[str]}
     * @memberof FetchSettlementsRequestFilters
     */
    'settlement_utrs'?: List[str];
    /**
     * Specify the start date from when you want the settlement reconciliation details.
     * @type {str}
     * @memberof FetchSettlementsRequestFilters
     */
    'start_date'?: str;
    /**
     * Specify the end date till when you want the settlement reconciliation details.
     * @type {str}
     * @memberof FetchSettlementsRequestFilters
     */
    'end_date'?: str;
}
