/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Payment link meta information object
 * @export
 * @interface LinkMetaResponseEntity
 */
export interface LinkMetaResponseEntity {
    /**
     * Notification URL for server-server communication. It should be an https URL.
     * @type {str}
     * @memberof LinkMetaResponseEntity
     */
    'notify_url'?: str;
    /**
     * If \"true\", link will directly open UPI Intent flow on mobile, and normal link flow elsewhere
     * @type {str}
     * @memberof LinkMetaResponseEntity
     */
    'upi_intent'?: str;
    /**
     * The URL to which user will be redirected to after the payment is done on the link. Maximum length: 250.
     * @type {str}
     * @memberof LinkMetaResponseEntity
     */
    'return_url'?: str;
    /**
     * Allowed payment modes for this link. Pass comma-separated values among following options - \"cc\", \"dc\", \"ccc\", \"ppc\", \"nb\", \"upi\", \"paypal\", \"app\". Leave it blank to show all available payment methods
     * @type {str}
     * @memberof LinkMetaResponseEntity
     */
    'payment_methods'?: str;
}
