/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payment link success creation response object
 * @export
 * @interface LinkEntity
 */
export interface LinkEntity {
    /**
     * 
     * @type {str}
     * @memberof LinkEntity
     */
    'cf_link_id'?: str;
    /**
     * 
     * @type {str}
     * @memberof LinkEntity
     */
    'link_id'?: str;
    /**
     * 
     * @type {str}
     * @memberof LinkEntity
     */
    'link_status'?: str;
    /**
     * 
     * @type {str}
     * @memberof LinkEntity
     */
    'link_currency'?: str;
    /**
     * 
     * @type {float}
     * @memberof LinkEntity
     */
    'link_amount'?: float;
    /**
     * 
     * @type {float}
     * @memberof LinkEntity
     */
    'link_amount_paid'?: float;
    /**
     * 
     * @type {bool}
     * @memberof LinkEntity
     */
    'link_partial_payments'?: bool;
    /**
     * 
     * @type {float}
     * @memberof LinkEntity
     */
    'link_minimum_partial_amount'?: float;
    /**
     * 
     * @type {str}
     * @memberof LinkEntity
     */
    'link_purpose'?: str;
    /**
     * 
     * @type {str}
     * @memberof LinkEntity
     */
    'link_created_at'?: str;
    /**
     * 
     * @type {LinkCustomerDetailsEntity}
     * @memberof LinkEntity
     */
    'customer_details'?: LinkCustomerDetailsEntity;
    /**
     * 
     * @type {LinkMetaResponseEntity}
     * @memberof LinkEntity
     */
    'link_meta'?: LinkMetaResponseEntity;
    /**
     * 
     * @type {str}
     * @memberof LinkEntity
     */
    'link_url'?: str;
    /**
     * 
     * @type {str}
     * @memberof LinkEntity
     */
    'link_expiry_time'?: str;
    /**
     * Key-value pair that can be used to store additional information about the entity. Maximum 5 key-value pairs
     * @type {Dict[str, str]}
     * @memberof LinkEntity
     */
    'link_notes'?: Dict[str, str];
    /**
     * 
     * @type {bool}
     * @memberof LinkEntity
     */
    'link_auto_reminders'?: bool;
    /**
     * 
     * @type {LinkNotifyEntity}
     * @memberof LinkEntity
     */
    'link_notify'?: LinkNotifyEntity;
    /**
     * Base64 encoded string for payment link. You can scan with camera to open a link in the browser to complete the payment.
     * @type {str}
     * @memberof LinkEntity
     */
    'link_qrcode'?: str;
    /**
     * 
     * @type {List[VendorSplit]}
     * @memberof LinkEntity
     */
    'order_splits'?: List[VendorSplit];
}
