/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Offer validation object
 * @export
 * @interface OfferValidationsResponse
 */
export interface OfferValidationsResponse {
    /**
     * Maximum Amount for Offer to be Applicable
     * @type {float}
     * @memberof OfferValidationsResponse
     */
    'max_allowed'?: float;
    /**
     * Minimum Amount for Offer to be Applicable
     * @type {float}
     * @memberof OfferValidationsResponse
     */
    'min_amount'?: float;
    /**
     * 
     * @type {OfferValidationsResponsePaymentMethod}
     * @memberof OfferValidationsResponse
     */
    'payment_method'?: OfferValidationsResponsePaymentMethod;
}
