/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Offer details and type
 * @export
 * @interface OfferDetails
 */
export interface OfferDetails {
    /**
     * Offer Type for the Offer.
     * @type {str}
     * @memberof OfferDetails
     */
    'offer_type': Offer_typeEnum;
    /**
     * 
     * @type {DiscountDetails}
     * @memberof OfferDetails
     */
    'discount_details'?: DiscountDetails;
    /**
     * 
     * @type {CashbackDetails}
     * @memberof OfferDetails
     */
    'cashback_details'?: CashbackDetails;
}

export const Offer_typeEnum = {
    'DISCOUNT': 'DISCOUNT',
    'CASHBACK': 'CASHBACK',
    'DISCOUNT_AND_CASHBACK': 'DISCOUNT_AND_CASHBACK',
    'NO_COST_EMI': 'NO_COST_EMI',
    'unknown_default_open_api': 'unknown_default_open_api'
} as const;

export type Offer_typeEnum = typeof Offer_typeEnum[keyof typeof Offer_typeEnum];

