/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The complete order extended data entity
 * @export
 * @interface OrderExtendedDataEntity
 */
export interface OrderExtendedDataEntity {
    /**
     * unique id generated by cashfree for your order
     * @type {str}
     * @memberof OrderExtendedDataEntity
     */
    'cf_order_id'?: str;
    /**
     * order_id sent during the api request
     * @type {str}
     * @memberof OrderExtendedDataEntity
     */
    'order_id'?: str;
    /**
     * 
     * @type {float}
     * @memberof OrderExtendedDataEntity
     */
    'order_amount'?: float;
    /**
     * Currency of the order. Example INR
     * @type {str}
     * @memberof OrderExtendedDataEntity
     */
    'order_currency'?: str;
    /**
     * When the order was created at cashfree's server
     * @type {datetime}
     * @memberof OrderExtendedDataEntity
     */
    'created_at'?: datetime;
    /**
     * 
     * @type {ChargesEntity}
     * @memberof OrderExtendedDataEntity
     */
    'charges'?: ChargesEntity;
    /**
     * 
     * @type {ExtendedCustomerDetails}
     * @memberof OrderExtendedDataEntity
     */
    'customer_details'?: ExtendedCustomerDetails;
    /**
     * 
     * @type {AddressDetails}
     * @memberof OrderExtendedDataEntity
     */
    'shipping_address'?: AddressDetails;
    /**
     * 
     * @type {AddressDetails}
     * @memberof OrderExtendedDataEntity
     */
    'billing_address'?: AddressDetails;
    /**
     * 
     * @type {ExtendedCartDetails}
     * @memberof OrderExtendedDataEntity
     */
    'cart'?: ExtendedCartDetails;
    /**
     * 
     * @type {OfferExtendedDetails}
     * @memberof OrderExtendedDataEntity
     */
    'offer'?: OfferExtendedDetails;
}
