/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * the data object pay api
 * @export
 * @interface OrderPayData
 */
export interface OrderPayData {
    /**
     * 
     * @type {str}
     * @memberof OrderPayData
     */
    'url'?: str;
    /**
     * 
     * @type {object}
     * @memberof OrderPayData
     */
    'payload'?: object;
    /**
     * 
     * @type {str}
     * @memberof OrderPayData
     */
    'content_type'?: str;
    /**
     * 
     * @type {str}
     * @memberof OrderPayData
     */
    'method'?: str;
    /**
     * 
     * @type {str}
     * @memberof OrderPayData
     */
    'redirect_to_bank'?: str;
}
