/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Order delivery Status associated with order.
 * @export
 * @interface OrderDeliveryStatus
 */
export interface OrderDeliveryStatus {
    /**
     * Delivery status of order
     * @type {str}
     * @memberof OrderDeliveryStatus
     */
    'status': StatusEnum;
    /**
     * Reason of provided order delivery status. This is optional field.
     * @type {str}
     * @memberof OrderDeliveryStatus
     */
    'reason'?: str;
}

export const StatusEnum = {
    'AWAITING_PICKUP': 'AWAITING_PICKUP',
    'CANCELLED': 'CANCELLED',
    'SELF_FULFILLED': 'SELF_FULFILLED',
    'PICKED_UP': 'PICKED_UP',
    'SHIPPED': 'SHIPPED',
    'IN_TRANSIT': 'IN_TRANSIT',
    'DELAY_COURIER_COMPANY_ISSUES': 'DELAY_COURIER_COMPANY_ISSUES',
    'DELAY_INCORRECT_ADDRESS': 'DELAY_INCORRECT_ADDRESS',
    'DELAY_SELLER_ISSUES': 'DELAY_SELLER_ISSUES',
    'REACHED_DESTINATION_HUB': 'REACHED_DESTINATION_HUB',
    'OUT_FOR_DELIVERY': 'OUT_FOR_DELIVERY',
    'DELIVERED': 'DELIVERED',
    'POTENTIAL_RTO_DELIVERY_ATTEMPTED': 'POTENTIAL_RTO_DELIVERY_ATTEMPTED',
    'RTO': 'RTO',
    'LOST': 'LOST',
    'DAMAGED': 'DAMAGED',
    'UNTRACKABLE_404': 'UNTRACKABLE_404',
    'MANUAL_INTERVENTION_BROKEN_URL': 'MANUAL_INTERVENTION_BROKEN_URL',
    'ASSOCIATED_WITH_RETURN_PICKUP': 'ASSOCIATED_WITH_RETURN_PICKUP',
    'UNSERVICEABLE': 'UNSERVICEABLE',
    'unknown_default_open_api': 'unknown_default_open_api'
} as const;

export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];

