/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * create refund request object
 * @export
 * @interface OrderCreateRefundRequest
 */
export interface OrderCreateRefundRequest {
    /**
     * Amount to be refunded. Should be lesser than or equal to the transaction amount. (Decimals allowed)
     * @type {float}
     * @memberof OrderCreateRefundRequest
     */
    'refund_amount': float;
    /**
     * An unique ID to associate the refund with. Provie alphanumeric values
     * @type {str}
     * @memberof OrderCreateRefundRequest
     */
    'refund_id': str;
    /**
     * A refund note for your reference.
     * @type {str}
     * @memberof OrderCreateRefundRequest
     */
    'refund_note'?: str;
    /**
     * Speed at which the refund is processed. It's an optional field with default being STANDARD
     * @type {str}
     * @memberof OrderCreateRefundRequest
     */
    'refund_speed'?: Refund_speedEnum;
    /**
     * 
     * @type {List[VendorSplit]}
     * @memberof OrderCreateRefundRequest
     */
    'refund_splits'?: List[VendorSplit];
}

export const Refund_speedEnum = {
    'STANDARD': 'STANDARD',
    'INSTANT': 'INSTANT',
    'unknown_default_open_api': 'unknown_default_open_api'
} as const;

export type Refund_speedEnum = typeof Refund_speedEnum[keyof typeof Refund_speedEnum];

