/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This is the response shared when merchant inovkes the OTP submit or resend API
 * @export
 * @interface OrderAuthenticateEntity
 */
export interface OrderAuthenticateEntity {
    /**
     * The payment id for which this request was sent
     * @type {str}
     * @memberof OrderAuthenticateEntity
     */
    'cf_payment_id'?: str;
    /**
     * The action that was invoked for this request.
     * @type {str}
     * @memberof OrderAuthenticateEntity
     */
    'action'?: ActionEnum;
    /**
     * Status of the is action. Will be either failed or successful. If the action is successful, you should still call the authorization status to verify the final payment status.
     * @type {str}
     * @memberof OrderAuthenticateEntity
     */
    'authenticate_status'?: Authenticate_statusEnum;
    /**
     * Human readable message which describes the status in more detail
     * @type {str}
     * @memberof OrderAuthenticateEntity
     */
    'payment_message'?: str;
}

export const ActionEnum = {
    'SUBMIT_OTP': 'SUBMIT_OTP',
    'RESEND_OTP': 'RESEND_OTP',
    'unknown_default_open_api': 'unknown_default_open_api'
} as const;

export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];
export const Authenticate_statusEnum = {
    'FAILED': 'FAILED',
    'SUCCESS': 'SUCCESS',
    'unknown_default_open_api': 'unknown_default_open_api'
} as const;

export type Authenticate_statusEnum = typeof Authenticate_statusEnum[keyof typeof Authenticate_statusEnum];

