/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentMethodCardInPaymentsEntityCard
 */
export interface PaymentMethodCardInPaymentsEntityCard {
    /**
     * 
     * @type {str}
     * @memberof PaymentMethodCardInPaymentsEntityCard
     */
    'channel'?: str;
    /**
     * 
     * @type {str}
     * @memberof PaymentMethodCardInPaymentsEntityCard
     */
    'card_number'?: str;
    /**
     * 
     * @type {str}
     * @memberof PaymentMethodCardInPaymentsEntityCard
     */
    'card_network'?: str;
    /**
     * 
     * @type {str}
     * @memberof PaymentMethodCardInPaymentsEntityCard
     */
    'card_type'?: str;
    /**
     * 
     * @type {str}
     * @memberof PaymentMethodCardInPaymentsEntityCard
     */
    'card_country'?: str;
    /**
     * 
     * @type {str}
     * @memberof PaymentMethodCardInPaymentsEntityCard
     */
    'card_bank_name'?: str;
    /**
     * 
     * @type {str}
     * @memberof PaymentMethodCardInPaymentsEntityCard
     */
    'card_network_reference_id'?: str;
    /**
     * 
     * @type {str}
     * @memberof PaymentMethodCardInPaymentsEntityCard
     */
    'instrument_id'?: str;
}
