/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The complete order entity
 * @export
 * @interface PaymentLinkOrderEntity
 */
export interface PaymentLinkOrderEntity {
    /**
     * unique id generated by cashfree for your order
     * @type {str}
     * @memberof PaymentLinkOrderEntity
     */
    'cf_order_id'?: str;
    /**
     * link id of the order
     * @type {str}
     * @memberof PaymentLinkOrderEntity
     */
    'link_id'?: str;
    /**
     * order_id sent during the api request
     * @type {str}
     * @memberof PaymentLinkOrderEntity
     */
    'order_id'?: str;
    /**
     * Type of the entity.
     * @type {str}
     * @memberof PaymentLinkOrderEntity
     */
    'entity'?: str;
    /**
     * Currency of the order. Example INR
     * @type {str}
     * @memberof PaymentLinkOrderEntity
     */
    'order_currency'?: str;
    /**
     * 
     * @type {float}
     * @memberof PaymentLinkOrderEntity
     */
    'order_amount'?: float;
    /**
     * Possible values are  - `ACTIVE`: Order does not have a sucessful transaction yet - `PAID`: Order is PAID with one successful transaction - `EXPIRED`: Order was not PAID and not it has expired. No transaction can be initiated for an EXPIRED order. 
     * @type {str}
     * @memberof PaymentLinkOrderEntity
     */
    'order_status'?: str;
    /**
     * 
     * @type {str}
     * @memberof PaymentLinkOrderEntity
     */
    'payment_session_id'?: str;
    /**
     * 
     * @type {str}
     * @memberof PaymentLinkOrderEntity
     */
    'order_expiry_time'?: str;
    /**
     * Additional note for order
     * @type {str}
     * @memberof PaymentLinkOrderEntity
     */
    'order_note'?: str;
    /**
     * When the order was created at cashfree's server
     * @type {str}
     * @memberof PaymentLinkOrderEntity
     */
    'created_at'?: str;
    /**
     * 
     * @type {List[VendorSplit]}
     * @memberof PaymentLinkOrderEntity
     */
    'order_splits'?: List[VendorSplit];
    /**
     * 
     * @type {PaymentLinkCustomerDetails}
     * @memberof PaymentLinkOrderEntity
     */
    'customer_details'?: PaymentLinkCustomerDetails;
    /**
     * 
     * @type {OrderMeta}
     * @memberof PaymentLinkOrderEntity
     */
    'order_meta'?: OrderMeta;
    /**
     * Custom Tags in thr form of {\"key\":\"value\"} which can be passed for an order. A maximum of 10 tags can be added
     * @type {Dict[str, str]}
     * @memberof PaymentLinkOrderEntity
     */
    'order_tags'?: Dict[str, str];
}
