# coding: utf-8

"""
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

The version of the OpenAPI document: 2026-01-01
Contact: developers@cashfree.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime


from pydantic import validate_arguments, ValidationError, Field, StrictStr, StrictBytes, StrictInt, StrictFloat, StrictBool, field_validator, BaseModel
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

class ProductConditionsEntity(BaseModel):
    """
    ProductConditionsEntity
    """
    action: Optional[StrictStr] = Field(default=None, description="The Action key in the conditions array specifies whether a condition is allowed or denied for the specified rule or feature.")
    key: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="key of the condition.")
    values: Optional[Annotated[List[StrictStr], Field(max_length=10)]] = Field(default=None, description="Values set for the condition.")
    __properties = ["action", "key", "values"]

    # Updated to Pydantic v2
    """Pydantic configuration"""
    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProductConditionsEntity:
        """Create an instance of ProductConditionsEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))
    
    @classmethod
    def from_json_for_one_of(cls, json_str: str) -> ProductConditionsEntity:
        """Create an instance of ProductConditionsEntity from a JSON string"""
        temp_dict = json.loads(json_str)
        if "action, key, values" in temp_dict.keys():
            return cls.from_dict(json.loads(json_str))
        return None

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProductConditionsEntity:
        """Create an instance of ProductConditionsEntity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProductConditionsEntity.parse_obj(obj)

        _obj = ProductConditionsEntity.parse_obj({
            "action": obj.get("action"),
            "key": obj.get("key"),
            "values": obj.get("values")
        })
        return _obj


# Pydantic v2: resolve forward references & Annotated types
ProductConditionsEntity.model_rebuild()

