/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Error when rate limit is breached for your api
 * @export
 * @interface RateLimitError
 */
export interface RateLimitError {
    /**
     * 
     * @type {str}
     * @memberof RateLimitError
     */
    'message'?: str;
    /**
     * 
     * @type {str}
     * @memberof RateLimitError
     */
    'code'?: str;
    /**
     * rate_limit_error
     * @type {str}
     * @memberof RateLimitError
     */
    'type'?: TypeEnum;
}

export const TypeEnum = {
    'rate_limit_error': 'rate_limit_error',
    'unknown_default_open_api': 'unknown_default_open_api'
} as const;

export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];

