/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SettlementReconEntityDataInnerSettlementDetails
 */
export interface SettlementReconEntityDataInnerSettlementDetails {
    /**
     * Unique ID to identify the settlement.
     * @type {str}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'cf_settlement_id'?: str;
    /**
     * Date and time when the settlement was processed.
     * @type {str}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'settlement_date'?: str;
    /**
     * Unique transaction reference number of the settlement.
     * @type {str}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'utr'?: str;
    /**
     * Service charge that is applicable for splitting the payment.
     * @type {float}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'split_service_charge'?: float;
    /**
     * Service tax applicable for splitting the amount to vendors.
     * @type {float}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'split_service_tax'?: float;
    /**
     * Vendor commission applicable for this transaction.
     * @type {float}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'vendor_commission'?: float;
    /**
     * Date and time from settlement computed.
     * @type {str}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'payment_from'?: str;
    /**
     * Date and time till settlement computed.
     * @type {str}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'payment_till'?: str;
    /**
     * If any reason for settlement failure.
     * @type {str}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'reason'?: str;
    /**
     * Remarks related for settlement.
     * @type {str}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'remarks'?: str;
    /**
     * Service charge for the transactions.
     * @type {float}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'service_charge'?: float;
    /**
     * Service tax for the transactions.
     * @type {float}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'service_tax'?: float;
    /**
     * Settlement Service Charge.
     * @type {float}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'settlement_charge'?: float;
    /**
     * Date and time when Settlement initiated.
     * @type {str}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'settlement_initiated_on'?: str;
    /**
     * Settlement Service Tax.
     * @type {float}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'settlement_tax'?: float;
    /**
     * Type of Settlement, Example - Normal Settlement.
     * @type {str}
     * @memberof SettlementReconEntityDataInnerSettlementDetails
     */
    'settlement_type'?: str;
}
