/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SettlementReconEntityDataInnerOrderDetails
 */
export interface SettlementReconEntityDataInnerOrderDetails {
    /**
     * Unique order ID. Alphanumeric and only '-' and '_' allowed.
     * @type {str}
     * @memberof SettlementReconEntityDataInnerOrderDetails
     */
    'order_id'?: str;
    /**
     * The amount which was passed at the order creation time.
     * @type {float}
     * @memberof SettlementReconEntityDataInnerOrderDetails
     */
    'order_amount'?: float;
    /**
     * Order Curreny type - INR.
     * @type {str}
     * @memberof SettlementReconEntityDataInnerOrderDetails
     */
    'order_currency'?: str;
    /**
     * The order tags provided during order creation
     * @type {object}
     * @memberof SettlementReconEntityDataInnerOrderDetails
     */
    'order_tags'?: object;
}
