/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface StaticQrResponseEntity
 */
export interface StaticQrResponseEntity {
    /**
     * cashfree terminal id
     * @type {int}
     * @memberof StaticQrResponseEntity
     */
    'cf_terminal_id'?: int;
    /**
     * Virtual Address
     * @type {str}
     * @memberof StaticQrResponseEntity
     */
    'vpa'?: str;
    /**
     * Status of vpa
     * @type {str}
     * @memberof StaticQrResponseEntity
     */
    'status'?: str;
    /**
     * qrcode
     * @type {str}
     * @memberof StaticQrResponseEntity
     */
    'qrCode'?: str;
}
