/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Static Split Request
 * @export
 * @interface StaticSplitRequest
 */
export interface StaticSplitRequest {
    /**
     * Specify if the split is to be active or not. Possible values: true/false
     * @type {bool}
     * @memberof StaticSplitRequest
     */
    'active': bool;
    /**
     * For Subscription payments, the subscription reference ID is to be shared as the terminal ID. Incase for Payment Gateway terminal ID is non-mandatory. Mention as 0 if not applicable.
     * @type {str}
     * @memberof StaticSplitRequest
     */
    'terminal_id'?: str;
    /**
     * You can share additional information using the reference ID.
     * @type {float}
     * @memberof StaticSplitRequest
     */
    'terminal_reference_id'?: float;
    /**
     * Specify the product for which the split should be created. If you want split to be created for Payment Gateway pass value as \"PG\". If you want split to be created for Subscription, pass value as \"SBC\". Accepted values - \"STATIC_QR\", \"SBC\", \"PG\", \"EPOS\".
     * @type {str}
     * @memberof StaticSplitRequest
     */
    'product_type': str;
    /**
     * Provide the split scheme details.
     * @type {List[StaticSplitRequestSchemeInner]}
     * @memberof StaticSplitRequest
     */
    'scheme': List[StaticSplitRequestSchemeInner];
}
