/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Subscription customer details.
 * @export
 * @interface SubscriptionCustomerDetails
 */
export interface SubscriptionCustomerDetails {
    /**
     * Name of the customer.
     * @type {str}
     * @memberof SubscriptionCustomerDetails
     */
    'customer_name'?: str;
    /**
     * Email of the customer.
     * @type {str}
     * @memberof SubscriptionCustomerDetails
     */
    'customer_email': str;
    /**
     * Phone number of the customer.
     * @type {str}
     * @memberof SubscriptionCustomerDetails
     */
    'customer_phone': str;
    /**
     * Bank holder name of the customer.
     * @type {str}
     * @memberof SubscriptionCustomerDetails
     */
    'customer_bank_account_holder_name'?: str;
    /**
     * Bank account number of the customer.
     * @type {str}
     * @memberof SubscriptionCustomerDetails
     */
    'customer_bank_account_number'?: str;
    /**
     * IFSC code of the customer.
     * @type {str}
     * @memberof SubscriptionCustomerDetails
     */
    'customer_bank_ifsc'?: str;
    /**
     * Bank code of the customer. Refer to https://www.npci.org.in/PDF/nach/live-members-e-mandates/Live-Banks-in-API-E-Mandate.pdf
     * @type {str}
     * @memberof SubscriptionCustomerDetails
     */
    'customer_bank_code'?: str;
    /**
     * Bank account type of the customer.
     * @type {str}
     * @memberof SubscriptionCustomerDetails
     */
    'customer_bank_account_type'?: str;
}
