/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The response returned for Get, Create or Manage Subscription APIs.
 * @export
 * @interface SubscriptionEntity
 */
export interface SubscriptionEntity {
    /**
     * 
     * @type {AuthorizationDetails}
     * @memberof SubscriptionEntity
     */
    'authorisation_details'?: AuthorizationDetails;
    /**
     * Cashfree subscription reference number
     * @type {str}
     * @memberof SubscriptionEntity
     */
    'cf_subscription_id'?: str;
    /**
     * 
     * @type {SubscriptionCustomerDetails}
     * @memberof SubscriptionEntity
     */
    'customer_details'?: SubscriptionCustomerDetails;
    /**
     * 
     * @type {PlanEntity}
     * @memberof SubscriptionEntity
     */
    'plan_details'?: PlanEntity;
    /**
     * Time at which the subscription will expire.
     * @type {str}
     * @memberof SubscriptionEntity
     */
    'subscription_expiry_time'?: str;
    /**
     * Time at which the first charge will be made for the subscription. Applicable only for PERIODIC plans.
     * @type {str}
     * @memberof SubscriptionEntity
     */
    'subscription_first_charge_time'?: str;
    /**
     * A unique ID passed by merchant for identifying the subscription.
     * @type {str}
     * @memberof SubscriptionEntity
     */
    'subscription_id'?: str;
    /**
     * 
     * @type {SubscriptionEntitySubscriptionMeta}
     * @memberof SubscriptionEntity
     */
    'subscription_meta'?: SubscriptionEntitySubscriptionMeta;
    /**
     * Note for the subscription.
     * @type {str}
     * @memberof SubscriptionEntity
     */
    'subscription_note'?: str;
    /**
     * Subscription Session Id.
     * @type {str}
     * @memberof SubscriptionEntity
     */
    'subscription_session_id'?: str;
    /**
     * Payment splits for the subscription.
     * @type {List[SubscriptionPaymentSplitItem]}
     * @memberof SubscriptionEntity
     */
    'subscription_payment_splits'?: List[SubscriptionPaymentSplitItem];
    /**
     * Status of the subscription.
     * @type {str}
     * @memberof SubscriptionEntity
     */
    'subscription_status'?: str;
    /**
     * Tags for the subscription.
     * @type {object}
     * @memberof SubscriptionEntity
     */
    'subscription_tags'?: object;
}
