/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The response returned in Get, Create or Manage Subscription Payment APIs.
 * @export
 * @interface SubscriptionPaymentEntity
 */
export interface SubscriptionPaymentEntity {
    /**
     * 
     * @type {AuthorizationDetails}
     * @memberof SubscriptionPaymentEntity
     */
    'authorization_details'?: AuthorizationDetails;
    /**
     * Cashfree subscription payment reference number
     * @type {str}
     * @memberof SubscriptionPaymentEntity
     */
    'cf_payment_id'?: str;
    /**
     * Cashfree subscription reference number
     * @type {str}
     * @memberof SubscriptionPaymentEntity
     */
    'cf_subscription_id'?: str;
    /**
     * Cashfree subscription payment transaction ID
     * @type {str}
     * @memberof SubscriptionPaymentEntity
     */
    'cf_txn_id'?: str;
    /**
     * Cashfree subscription payment order ID
     * @type {str}
     * @memberof SubscriptionPaymentEntity
     */
    'cf_order_id'?: str;
    /**
     * 
     * @type {SubscriptionPaymentEntityFailureDetails}
     * @memberof SubscriptionPaymentEntity
     */
    'failure_details'?: SubscriptionPaymentEntityFailureDetails;
    /**
     * The charge amount of the payment.
     * @type {float}
     * @memberof SubscriptionPaymentEntity
     */
    'payment_amount'?: float;
    /**
     * A unique ID passed by merchant for identifying the transaction.
     * @type {str}
     * @memberof SubscriptionPaymentEntity
     */
    'payment_id'?: str;
    /**
     * The date on which the payment was initiated.
     * @type {str}
     * @memberof SubscriptionPaymentEntity
     */
    'payment_initiated_date'?: str;
    /**
     * Payment remarks.
     * @type {str}
     * @memberof SubscriptionPaymentEntity
     */
    'payment_remarks'?: str;
    /**
     * The date on which the payment is scheduled to be processed.
     * @type {str}
     * @memberof SubscriptionPaymentEntity
     */
    'payment_schedule_date'?: str;
    /**
     * Status of the payment.
     * @type {str}
     * @memberof SubscriptionPaymentEntity
     */
    'payment_status'?: str;
    /**
     * Payment type. Can be AUTH or CHARGE.
     * @type {str}
     * @memberof SubscriptionPaymentEntity
     */
    'payment_type'?: str;
    /**
     * Retry attempts.
     * @type {int}
     * @memberof SubscriptionPaymentEntity
     */
    'retry_attempts'?: int;
    /**
     * A unique ID passed by merchant for identifying the subscription.
     * @type {str}
     * @memberof SubscriptionPaymentEntity
     */
    'subscription_id'?: str;
}
