/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * object when you are using preauth in UPI in order pay
 * @export
 * @interface UPIAuthorizeDetails
 */
export interface UPIAuthorizeDetails {
    /**
     * Time by which this authorization should be approved by the customer.
     * @type {str}
     * @memberof UPIAuthorizeDetails
     */
    'approve_by'?: str;
    /**
     * This is the time when the UPI one time mandate will start
     * @type {str}
     * @memberof UPIAuthorizeDetails
     */
    'start_time'?: str;
    /**
     * This is the time when the UPI mandate will be over. If the mandate has not been executed by this time, the funds will be returned back to the customer after this time.
     * @type {str}
     * @memberof UPIAuthorizeDetails
     */
    'end_time'?: str;
}
