# coding: utf-8

"""
Cashfree Payment Gateway APIs

Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

The version of the OpenAPI document: 2026-01-01
Contact: developers@cashfree.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime


from pydantic import validate_arguments, ValidationError, Field, StrictStr, StrictBytes, StrictInt, StrictFloat, StrictBool, field_validator, BaseModel
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

class VendorRecon200ResponseDataInner(BaseModel):
    """
    VendorRecon200ResponseDataInner
    """
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    settlement_eligibility_time: Optional[StrictStr] = None
    merchant_order_id: Optional[StrictStr] = None
    tx_time: Optional[StrictStr] = None
    settlement_id: Optional[StrictInt] = None
    settled: Optional[StrictBool] = None
    fee: Optional[StrictStr] = None
    tax: Optional[StrictStr] = None
    entity_id: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    merchant_vendor_id: Optional[StrictStr] = None
    added_on_time: Optional[StrictStr] = None
    settlement_time: Optional[StrictStr] = None
    settlement_utr: Optional[StrictStr] = None
    currency: Optional[StrictStr] = None
    debit: Optional[StrictStr] = None
    credit: Optional[StrictStr] = None
    refund_arn: Optional[StrictStr] = None
    __properties = ["amount", "settlement_eligibility_time", "merchant_order_id", "tx_time", "settlement_id", "settled", "fee", "tax", "entity_id", "type", "merchant_vendor_id", "added_on_time", "settlement_time", "settlement_utr", "currency", "debit", "credit", "refund_arn"]

    # Updated to Pydantic v2
    """Pydantic configuration"""
    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VendorRecon200ResponseDataInner:
        """Create an instance of VendorRecon200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))
    
    @classmethod
    def from_json_for_one_of(cls, json_str: str) -> VendorRecon200ResponseDataInner:
        """Create an instance of VendorRecon200ResponseDataInner from a JSON string"""
        temp_dict = json.loads(json_str)
        if "amount, settlement_eligibility_time, merchant_order_id, tx_time, settlement_id, settled, fee, tax, entity_id, type, merchant_vendor_id, added_on_time, settlement_time, settlement_utr, currency, debit, credit, refund_arn" in temp_dict.keys():
            return cls.from_dict(json.loads(json_str))
        return None

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VendorRecon200ResponseDataInner:
        """Create an instance of VendorRecon200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VendorRecon200ResponseDataInner.parse_obj(obj)

        _obj = VendorRecon200ResponseDataInner.parse_obj({
            "amount": obj.get("amount"),
            "settlement_eligibility_time": obj.get("settlement_eligibility_time"),
            "merchant_order_id": obj.get("merchant_order_id"),
            "tx_time": obj.get("tx_time"),
            "settlement_id": obj.get("settlement_id"),
            "settled": obj.get("settled"),
            "fee": obj.get("fee"),
            "tax": obj.get("tax"),
            "entity_id": obj.get("entity_id"),
            "type": obj.get("type"),
            "merchant_vendor_id": obj.get("merchant_vendor_id"),
            "added_on_time": obj.get("added_on_time"),
            "settlement_time": obj.get("settlement_time"),
            "settlement_utr": obj.get("settlement_utr"),
            "currency": obj.get("currency"),
            "debit": obj.get("debit"),
            "credit": obj.get("credit"),
            "refund_arn": obj.get("refund_arn")
        })
        return _obj


# Pydantic v2: resolve forward references & Annotated types
VendorRecon200ResponseDataInner.model_rebuild()

