# coding: utf-8

"""
    New Payment Gateway APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2022-01-01
    Contact: nextgenapi@cashfree.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from cashfree_pg_sdk_python.configuration import Configuration


class CFAuthorizationRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'action': 'str',
        'amount': 'float'
    }

    attribute_map = {
        'action': 'action',
        'amount': 'amount'
    }

    def __init__(self, action=None, amount=None, local_vars_configuration=None):  # noqa: E501
        """CFAuthorizationRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._action = None
        self._amount = None
        self.discriminator = None

        if action is not None:
            self.action = action
        if amount is not None:
            self.amount = amount

    @property
    def action(self):
        """Gets the action of this CFAuthorizationRequest.  # noqa: E501

        Type of authorization to run. Can be one of 'CAPTURE' , 'VOID'  # noqa: E501

        :return: The action of this CFAuthorizationRequest.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this CFAuthorizationRequest.

        Type of authorization to run. Can be one of 'CAPTURE' , 'VOID'  # noqa: E501

        :param action: The action of this CFAuthorizationRequest.  # noqa: E501
        :type action: str
        """
        allowed_values = ["CAPTURE", "VOID"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and action not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `action` ({0}), must be one of {1}"  # noqa: E501
                .format(action, allowed_values)
            )

        self._action = action

    @property
    def amount(self):
        """Gets the amount of this CFAuthorizationRequest.  # noqa: E501

        The amount if you are running a 'CAPTURE'  # noqa: E501

        :return: The amount of this CFAuthorizationRequest.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this CFAuthorizationRequest.

        The amount if you are running a 'CAPTURE'  # noqa: E501

        :param amount: The amount of this CFAuthorizationRequest.  # noqa: E501
        :type amount: float
        """

        self._amount = amount

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CFAuthorizationRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CFAuthorizationRequest):
            return True

        return self.to_dict() != other.to_dict()
