# coding: utf-8

"""
    New Payment Gateway APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2022-01-01
    Contact: nextgenapi@cashfree.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from cashfree_pg_sdk_python.configuration import Configuration


class CFUPIAuthorizeDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'approve_by': 'str',
        'start_time': 'str',
        'end_time': 'str'
    }

    attribute_map = {
        'approve_by': 'approve_by',
        'start_time': 'start_time',
        'end_time': 'end_time'
    }

    def __init__(self, approve_by=None, start_time=None, end_time=None, local_vars_configuration=None):  # noqa: E501
        """CFUPIAuthorizeDetails - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._approve_by = None
        self._start_time = None
        self._end_time = None
        self.discriminator = None

        if approve_by is not None:
            self.approve_by = approve_by
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time

    @property
    def approve_by(self):
        """Gets the approve_by of this CFUPIAuthorizeDetails.  # noqa: E501

        Time by which this authorization should be approved by the customer.  # noqa: E501

        :return: The approve_by of this CFUPIAuthorizeDetails.  # noqa: E501
        :rtype: str
        """
        return self._approve_by

    @approve_by.setter
    def approve_by(self, approve_by):
        """Sets the approve_by of this CFUPIAuthorizeDetails.

        Time by which this authorization should be approved by the customer.  # noqa: E501

        :param approve_by: The approve_by of this CFUPIAuthorizeDetails.  # noqa: E501
        :type approve_by: str
        """

        self._approve_by = approve_by

    @property
    def start_time(self):
        """Gets the start_time of this CFUPIAuthorizeDetails.  # noqa: E501

        This is the time when the UPI one time mandate will start  # noqa: E501

        :return: The start_time of this CFUPIAuthorizeDetails.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this CFUPIAuthorizeDetails.

        This is the time when the UPI one time mandate will start  # noqa: E501

        :param start_time: The start_time of this CFUPIAuthorizeDetails.  # noqa: E501
        :type start_time: str
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this CFUPIAuthorizeDetails.  # noqa: E501

        This is the time when the UPI mandate will be over. If the mandate has not been executed by this time, the funds will be returned back to the customer after this time.  # noqa: E501

        :return: The end_time of this CFUPIAuthorizeDetails.  # noqa: E501
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this CFUPIAuthorizeDetails.

        This is the time when the UPI mandate will be over. If the mandate has not been executed by this time, the funds will be returned back to the customer after this time.  # noqa: E501

        :param end_time: The end_time of this CFUPIAuthorizeDetails.  # noqa: E501
        :type end_time: str
        """

        self._end_time = end_time

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CFUPIAuthorizeDetails):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CFUPIAuthorizeDetails):
            return True

        return self.to_dict() != other.to_dict()
