# coding: utf-8

"""
    Cashfree Payment Gateway APIs

    Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.

    The version of the OpenAPI document: 2022-09-01
    Contact: developers@cashfree.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import cashfree_pg
from cashfree_pg.models.w_hdata import WHdata  # noqa: E501
from cashfree_pg.rest import ApiException

class TestWHdata(unittest.TestCase):
    """WHdata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WHdata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WHdata`
        """
        model = cashfree_pg.models.w_hdata.WHdata()  # noqa: E501
        if include_optional :
            return WHdata(
                order = {"order_id":"1633615918","order_amount":1,"order_currency":"INR","order_tags":{"name":"john"}}, 
                payment = {"$ref":"#/components/examples/payments_entity_list_example/value/0"}, 
                customer_details = {"$ref":"#/components/schemas/CustomerDetails/example"}
            )
        else :
            return WHdata(
        )
        """

    def testWHdata(self):
        """Test WHdata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
